[package]
name = "igneous-editor"
description = "The note editor widget for Igneous"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
adw.workspace = true
gtk.workspace = true
igneous-markdown.workspace = true
nucleo-matcher.workspace = true
sourceview.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
glib-build-tools.workspace = true
