[package]
name = "igneous-markdown"
description = "Obsidian Flavoured Markdown model for Igneous"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
pulldown-cmark.workspace = true
regex.workspace = true
saphyr.workspace = true
smallvec.workspace = true
thiserror.workspace = true

[dev-dependencies]
igneous-core.workspace = true
insta.workspace = true
proptest.workspace = true
