[package]
name = "igneous-lint"
description = "Markdown and YAML linter for Igneous"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
igneous-core.workspace = true
igneous-markdown.workspace = true
jiff.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
